<?php

declare(strict_types = 1);

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

$config = new Config;

return $config->
	setRiskyAllowed(true)->
	setIndent("\t")->
	setUsingCache(true)->
	setRules([
		'align_multiline_comment' => true,
		'array_indentation' => true,
		'array_push' => true,
		'array_syntax' => true,
		'assign_null_coalescing_to_coalesce_equal' => true,
		'backtick_to_shell_exec' => true,
		'binary_operator_spaces' => true,
		'blank_line_after_namespace' => true,
		'blank_line_after_opening_tag' => true,
		'blank_line_before_statement' => true,
		'blank_line_between_import_groups' => true,
		'cast_spaces' => true,
		'class_attributes_separation' => true,
		'class_definition' => true,
		'class_reference_name_casing' => true,
		'clean_namespace' => true,
		'combine_consecutive_issets' => true,
		'combine_consecutive_unsets' => true,
		'combine_nested_dirname' => true,
		'compact_nullable_typehint' => true,
		'concat_space' => ['spacing' => 'one'],
		'constant_case' => true,
		'control_structure_braces' => true,
		'control_structure_continuation_position' => true,
		'curly_braces_position' => true,
		'declare_equal_normalize' => ['space' => 'single'],
		'declare_parentheses' => true,
		'declare_strict_types' => true,
		'dir_constant' => true,
		'doctrine_annotation_array_assignment' => true,
		'doctrine_annotation_braces' => true,
		'doctrine_annotation_indentation' => true,
		'doctrine_annotation_spaces' => true,
		'echo_tag_syntax' => true,
		'elseif' => true,
		'empty_loop_body' => true,
		'empty_loop_condition' => true,
		'encoding' => true,
		'ereg_to_preg' => true,
		'explicit_indirect_variable' => true,
		'explicit_string_variable' => true,
		'full_opening_tag' => true,
		'fully_qualified_strict_types' => true,
		'function_declaration' => true,
		'function_typehint_space' => true,
		'general_phpdoc_annotation_remove' => true,
		'general_phpdoc_tag_rename' => true,
		'global_namespace_import' => true,
		'heredoc_indentation' => true,
		'heredoc_to_nowdoc' => true,
		'implode_call' => true,
		'include' => true,
		'increment_style' => ['style' => 'post'],
		'indentation_type' => true,
		'integer_literal_case' => true,
		'lambda_not_used_import' => true,
		'line_ending' => true,
		'linebreak_after_opening_tag' => true,
		'list_syntax' => true,
		'logical_operators' => true,
		'lowercase_cast' => true,
		'lowercase_keywords' => true,
		'lowercase_static_reference' => true,
		'magic_constant_casing' => true,
		'magic_method_casing' => true,
		'method_argument_space' => true,
		'method_chaining_indentation' => true,
		'modernize_strpos' => true,
		'modernize_types_casting' => true,
		'multiline_comment_opening_closing' => true,
		'multiline_whitespace_before_semicolons' => true,
		'native_function_casing' => true,
		'native_function_type_declaration_casing' => true,
		'new_with_braces' => ['anonymous_class' => false, 'named_class' => false],
		'no_alias_language_construct_call' => true,
		'no_alternative_syntax' => true,
		'no_binary_string' => true,
		'no_blank_lines_after_class_opening' => true,
		'no_blank_lines_after_phpdoc' => true,
		'no_blank_lines_before_namespace' => false,
		'no_break_comment' => true,
		'no_closing_tag' => true,
		'no_empty_comment' => true,
		'no_empty_phpdoc' => true,
		'no_empty_statement' => true,
		'no_extra_blank_lines' => true,
		'no_leading_import_slash' => true,
		'no_leading_namespace_whitespace' => true,
		'no_mixed_echo_print' => ['use' => 'print'],
		'no_multiline_whitespace_around_double_arrow' => true,
		'no_multiple_statements_per_line' => true,
		'no_null_property_initialization' => true,
		'no_short_bool_cast' => true,
		'no_singleline_whitespace_before_semicolons' => true,
		'no_space_around_double_colon' => true,
		'no_spaces_after_function_name' => true,
		'no_spaces_around_offset' => true,
		'no_spaces_inside_parenthesis' => true,
		'no_superfluous_phpdoc_tags' => true,
		'no_trailing_whitespace' => true,
		'no_trailing_whitespace_in_comment' => true,
		'no_unneeded_control_parentheses' => true,
		'no_unneeded_curly_braces' => true,
		'no_unneeded_import_alias' => true,
		'no_unset_cast' => true,
		'no_unused_imports' => true,
		'no_useless_concat_operator' => true,
		'no_useless_else' => true,
		'no_useless_nullsafe_operator' => true,
		'no_useless_return' => true,
		'no_whitespace_before_comma_in_array' => ['after_heredoc' => true],
		'no_whitespace_in_blank_line' => true,
		'normalize_index_brace' => true,
		'nullable_type_declaration_for_default_null_value' => true,
		'object_operator_without_whitespace' => true,
		'operator_linebreak' => ['position' => 'end'],
		'ordered_class_elements' => true,
		'ordered_imports' => true,
		'ordered_interfaces' => true,
		'php_unit_method_casing' => true,
		'php_unit_strict' => true,
		'php_unit_test_class_requires_covers' => true,
		'phpdoc_add_missing_param_annotation' => true,
		'phpdoc_align' => true,
		'phpdoc_annotation_without_dot' => true,
		'phpdoc_indent' => true,
		'phpdoc_inline_tag_normalizer' => true,
		'phpdoc_line_span' => true,
		'phpdoc_no_access' => true,
		'phpdoc_no_alias_tag' => true,
		'phpdoc_no_empty_return' => true,
		'phpdoc_no_package' => true,
		'phpdoc_no_useless_inheritdoc' => true,
		'phpdoc_order' => true,
		'phpdoc_order_by_value' => true,
		'phpdoc_return_self_reference' => true,
		'phpdoc_scalar' => true,
		'phpdoc_separation' => true,
		'phpdoc_single_line_var_spacing' => true,
		'phpdoc_summary' => true,
		'phpdoc_tag_type' => true,
		'phpdoc_to_comment' => true,
		'phpdoc_trim' => true,
		'phpdoc_trim_consecutive_blank_line_separation' => true,
		'phpdoc_types' => true,
		'phpdoc_types_order' => true,
		'phpdoc_var_annotation_correct_order' => true,
		'pow_to_exponentiation' => true,
		'return_type_declaration' => true,
		'semicolon_after_instruction' => true,
		'set_type_to_cast' => true,
		'short_scalar_cast' => true,
		'simple_to_complex_string_variable' => true,
		'simplified_if_return' => true,
		'simplified_null_return' => true,
		'single_blank_line_at_eof' => true,
		'single_blank_line_before_namespace' => true,
		'single_class_element_per_statement' => true,
		'single_import_per_statement' => true,
		'single_line_after_imports' => true,
		'single_line_comment_spacing' => true,
		'single_line_comment_style' => true,
		'single_line_throw' => true,
		'single_quote' => ['strings_containing_single_quote_chars' => true],
		'single_space_around_construct' => true,
		'single_trait_insert_per_statement' => true,
		'space_after_semicolon' => ['remove_in_empty_for_expressions' => false],
		'standardize_increment' => true,
		'standardize_not_equals' => true,
		'statement_indentation' => true,
		'strict_comparison' => true,
		'switch_case_semicolon_to_colon' => true,
		'switch_case_space' => true,
		'ternary_operator_spaces' => true,
		'ternary_to_null_coalescing' => true,
		'trailing_comma_in_multiline' => ['after_heredoc' => true],
		'trim_array_spaces' => true,
		'types_spaces' => ['space' => 'single'],
		'visibility_required' => ['elements' => ['const', 'method', 'property']],
		'void_return' => true,
		'whitespace_after_comma_in_array' => ['ensure_single_space' => true],
		'yoda_style' => ['always_move_variable' => true, 'less_and_greater' => true],
	])->
	setFinder(
		Finder::create()->
			in([
				__DIR__ . '/app',
				__DIR__ . '/config',
				__DIR__ . '/tests',
                __DIR__ . '/database',
				__DIR__ . '/routes',
			])->
			name('*.php')->
			notName('*.blade.php')->
			ignoreDotFiles(true)->
			ignoreVCS(true)
	);
